# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ESSI::FileSetMetadata
  include ESSI::RemoteLookupMetadata
  include ::Hyrax::FileSetBehavior

  self.indexer = ESSI::FileSetIndexer

  def collection_branding_info
    @collection_branding_info ||= CollectionBrandingInfo.where(file_set_id: self.id).first
  end

  def collection_branding?
    collection_branding_info.present?
  end

  def ocr_language
    [language.entries,
     parent&.language&.entries,
     ESSI.config.dig(:essi, :ocr_language),
     'eng'].map { |l| Tesseract.try_languages(l) }.select(&:present?).first
  end
end
